sudo: false
language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --skip-ghc-check setup
- stack --no-terminal --skip-ghc-check build --test --haddock --only-snapshot --fast --pedantic

script:
  - stack --no-terminal --skip-ghc-check test --fast --pedantic
  - stack --no-terminal --skip-ghc-check haddock --fast --pedantic
